export const MODULE_KEYS = {
  coreCatalog: "core_catalog",
  home: "home",
  search: "search",
  streaming: "streaming",
  downloads: "downloads",
  remix: "remix",
  proPlan: "pro_plan",
  trending: "trending",
  latest: "latest",
  top50: "top50",
  allTime: "all_time",
  genres: "genres",
  artists: "artists",
  albums: "albums",
  heroBanners: "hero_banners",
  editorPicks: "editor_picks",
  popularArtists: "popular_artists",
  events: "events",
  testimonials: "testimonials",
  topDownloads: "top_downloads",
  continueListening: "continue_listening",
  browseByGenre: "browse_by_genre",
  playlists: "playlists",
  favorites: "favorites",
  library: "library",
  recentlyPlayed: "recently_played",
  comments: "comments",
  likes: "likes",
  follows: "follows",
  notifications: "notifications",
  userRegistration: "user_registration",
  artistRegistration: "artist_registration",
  contactSupport: "contact_support",
  advertisingRequests: "advertising_requests",
  songRequests: "song_requests",
  songRemovalRequests: "song_removal_requests",
  upload: "upload",
  adminDashboard: "admin_dashboard",
  adminSongs: "admin_songs",
  adminArtists: "admin_artists",
  adminGenres: "admin_genres",
  adminAlbums: "admin_albums",
  adminMusicTypes: "admin_music_types",
  adminHeroBanners: "admin_hero_banners",
  adminEditorPicks: "admin_editor_picks",
  adminTrending: "admin_trending",
  adminUsers: "admin_users",
  adminMessages: "admin_messages",
  adminModules: "admin_modules",
  adminSettings: "admin_settings",
} as const;

export type ModuleKey = (typeof MODULE_KEYS)[keyof typeof MODULE_KEYS];
export type ModuleFlags = Record<string, boolean>;
